### ISSUE TITLE
polish up the doc and how to introduce zipkin into the php app?

### ISSUE THREAD

**Issue by maoling** [openzipkin/zipkin-php-example#11]
- I am javaer,not familar with php(the best language in the world).when run the example, fail in the `backend.php` Line6
  `require_once __DIR__ . '/vendor/autoload.php';`
  when run `composer install`, everything is ok.Do we need to polish up the doc for beginner like me?if so,I can give a PR.
- the traces of this example is too simple,can we do some random calls to make the traces more sophisticated, let users see the zipkin's power?
- if our PHP applications use zipkin,Does zipkin intrude too much into origin PHP codes?e,g
    ```
         $span->setKind(Zipkin\Kind\SERVER);
         $span->setName('parse_request');
    ```

   Does PHP has something like filter,annotation or AOP?

**Comment by maoling** [comment]
ping @jcchavezs

**Comment by maoling** [comment]
@jcchavezs 
- I saw the doc has updated.Thanks for your instant feedback. 

> Well, this is the example but usually instrumentation goes to frameworks or libraries and in that case, every library has a purpose and thus an specific kind e.g. in guzzle.

- forgive my almost zero php knowledge, I really want to konw if introduce zipkin,whether every php service/method,
we need to add this:
`$span->setKind(Zipkin\Kind\SERVER);     
     $span->setName('parse_request');`

**Comment by jcchavezs** [comment]
Hi @maoling not really. If you introduce zipkin and you are using a server framework (e.g. Symfony, Zend or Laravel) then you just need to plug a library (e.g. https://github.com/jcchavezs/zipkin-instrumentation-symfony) and it will do the trick for you. Same for http clients and db libraries.

So to be clear **no application logic should include tracing code**.

**Comment by maoling** [comment]
@jcchavezs  I get your idea。
where can I find the library about the `Laravel`?

**Comment by jcchavezs** [comment]
Unfortunately there is no one yet but if you are up to write one you can
have a look at the Symfony one:
https://github.com/jcchavezs/zipkin-instrumentation-symfony

José Carlos Chávez


Den fre. 16. nov. 2018 kl. 04:05 skrev 毛蛤丝 <notifications@github.com>:

**Comment by maoling** [comment]
@jcchavezs  
Thanks for your patient help.let me close this issue.

**Comment by jcchavezs** [comment]
You are welcome, let me know if you have need help trying to write the
laravel one.

José Carlos Chávez


Den fre. 16. nov. 2018 kl. 12:41 skrev 毛蛤丝 <notifications@github.com>:

**Comment by maoling** [comment]
@jcchavezs 
haha,of course. It couldn't be better if you can write an laravel instrument(smirk).

**Comment by jcchavezs** [comment]
Haha I have limited time but also limited experience with laravel but yeah
I am always happy to review PRs!

Den man. 19. nov. 2018, 12:31 skrev 毛蛤丝 <notifications@github.com:

**Comment by maoling** [comment]
@jcchavezs  
yes! writing a `laravel` one is on my agenda.

**Comment by maoling** [comment]
refer to this [project](https://github.com/drefined/php-zipkin),I have written a `laravel` instrument.
@jcchavezs 
Do you have a plan to integrate your `Symfony` one to the `openzipkin/zipkin-php-example` project :
https://github.com/jcchavezs/zipkin-instrumentation-symfony

**Comment by jcchavezs** [comment]
I think we could include the example in the same project. Could you drop
here the link for your laravel instrumentation?

Den tor. 6. des. 2018, 10:02 skrev 毛蛤丝 <notifications@github.com:

**Comment by jcchavezs** [comment]
I see, I believe that library only supports v1 (which has been deprecated,
see https://github.com/openzipkin/zipkin/releases/tag/2.10.1)

OTOH we only support the official zipkin-php version. If you want to write
a laravel instrumentation on top of official zipkin-php I can provide you
guidence, otherwise I don't think so.

Thanks for coming by tho!

Den tor. 6. des. 2018, 10:28 skrev 毛蛤丝 <notifications@github.com:
